// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdqtjgzlobdfirqgcwfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkcXRqZ3psb2JkZmlycWdjd2ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjQ4NTEsImV4cCI6MjA2OTkwMDg1MX0.yw4N6zGUZBfe-sW0pM8KEHC1hkhGitMeHoEgqGosj44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});